name: TIS Device Manager
version: "1.0.0"
slug: tis_device_manager
description: Open TIS Device Manager for Home Assistant (auto-detect IP-COM)
startup: application
boot: auto
host_network: true
ingress: false
panel_icon: mdi:cog-outline
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
ports:
  8080/tcp: 8080
options: {}
schema: {}
