name: TIS Device Manager
version: "0.1.0"
slug: tis_device_manager
description: Open-source TIS Device Manager for Home Assistant
startup: application
boot: auto
host_network: true
options: {}
schema: {}
arch:
  - aarch64
  - armv7
  - armhf
  - amd64
ingress: false
panel_icon: mdi:cog-outline
ports:
  8080/tcp: 8080
