name: TIS Device Manager
version: "0.1.0"
slug: tis_device_manager
description: "Custom TIS device manager backend"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
host_network: true
init: false
options: {}
schema: {}
ports: {}
ports_description: {}
map:
  - share:rw
